name: NodeJS

run-name : ${{github.actor}} is testing Projet NodeJS

on:
  push:
    branches: [ "main" ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}

        - run: npm install
        
        - run: npm test

        - run: npm install --global vercel@latest

        - run: vercel pull --yes --environment=preview --token=0Hh4Km2vsHAHo1SA4hZgOTkc

        - run: vercel build --token=0Hh4Km2vsHAHo1SA4hZgOTkc

        - run: vercel deploy --prebuilt --prod --token=0Hh4Km2vsHAHo1SA4hZgOTkc